# https://wlsdn3004.tistory.com/30
namespaceOverride: "monitoring"

alertmanagerSpec:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: alertmanager

prometheus:
  prometheusSpec:
    topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: topology.kubernetes.io/zone
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: prometheus
    thanos:
      image: quay.io/thanos/thanos:v0.28.1
      objectStorageConfig:
        key: secret-monitoring-thanos-s3
        name: config
  thanosService:
    enabled: true

thanosRulerSpec:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: thanos-ruler
