namespaceOverride: "monitoring"

alertmanagerSpec:
  replicas: 2
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: alertmanager

prometheus:
  serviceAccount:
    create: true
    name: ""
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::474156821902:role/thanos"
    automountServiceAccountToken: true
  replicas: 2
  prometheusSpec:
    topologySpreadConstraints:
      - maxSkew: 1

thanosRulerSpec:
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: thanos-ruler
