namespaceOverride: "monitoring"

existingObjstoreSecret: secret-monitoring-thanos-s3

query:
  enabled: true

  dnsDiscovery:
    enabled: true
    sidecarsService: kube-prometheus-stack-thanos-discovery
    sidecarsNamespace: monitoring

  replicaCount: 2

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: query
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: query

queryFrontend:
  service:
    type: NodePort
    nodePorts:
      http: 31004

storegateway:
  enabled: true
  persistence:
    enabled: false
  replicaCount: 2

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: storegateway
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: storegateway

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::474156821902:role/thanos

# This is used to inspect bucket blocks from a Web UI.
# bucketweb:
#   enabled: true
#   serviceAccount:
#     annotations:
#       eks.amazonaws.com/role-arn: arn:aws:iam::474156821902:role/thanos

compactor:
  enabled: true
  persistence:
    enabled: false

  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: thanos-compactor
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: DoNotSchedule
      labelSelector:
        matchLabels:
          app: thanos-compactor

  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::474156821902:role/thanos

ruler:
  enabled: false
